const COMMON = {
  country: 'AR', province: null, municipality: null,
  activityType: 'oficina',
  validationType: 'manual-and-automatic',
  requiresProfessionalReview: true,
  effectiveFrom: '1979-05-22',
  effectiveTo: null,
};

module.exports = [
  {
    ...COMMON,
    id: 'AR-LEY-19587-FRAMEWORK',
    title: 'Marco general de higiene y seguridad en el trabajo',
    source: 'Ley Nacional 19.587',
    sourceSection: 'Ámbito y principios generales',
    summary: 'Requiere evaluar las condiciones de higiene y seguridad del establecimiento y proteger la vida e integridad de las personas trabajadoras.',
    severity: 'high',
    sourceUrl: 'https://www.argentina.gob.ar/normativa/nacional/ley-19587-17612',
    checkedAt: '2026-08-07',
    ruleVersion: '1.0.0',
    effectiveFrom: '1972-04-28',
    requiredInputs: ['buildingUse', 'numberOfFloors', 'riskClassification.value'],
  },
  {
    ...COMMON,
    id: 'AR-DEC-351-79-FIRE-PROTECTION',
    title: 'Protección contra incendios',
    source: 'Decreto 351/79',
    sourceSection: 'Capítulo 18, artículos 160 a 187 / Anexo VII',
    summary: 'La evaluación debe considerar condiciones constructivas, medios de escape y medios de extinción adecuados al uso, ocupación y riesgo.',
    severity: 'critical',
    sourceUrl: 'https://www.argentina.gob.ar/normativa/recurso/32030/dto351-1979-anexo7/htm',
    checkedAt: '2026-08-07',
    ruleVersion: '1.0.0',
    requiredInputs: ['riskClassification.value', 'fireProtection.extinguishers.present'],
  },
  {
    ...COMMON,
    id: 'AR-DEC-351-79-MEANS-OF-EGRESS',
    title: 'Medios de escape',
    source: 'Decreto 351/79',
    sourceSection: 'Capítulo 18 / Anexo VII',
    summary: 'Los recorridos y salidas deben analizarse según la ocupación, el riesgo y la configuración real; esta regla no presume medidas que el plano no permite verificar.',
    severity: 'critical',
    sourceUrl: 'https://www.argentina.gob.ar/normativa/recurso/32030/dto351-1979-anexo7/htm',
    checkedAt: '2026-08-07',
    ruleVersion: '1.0.0',
    requiredInputs: ['maximumOccupancy', 'buildingStatus', 'numberOfFloors', 'egress.exitCount'],
  },
  {
    ...COMMON,
    id: 'AR-DEC-351-79-OFFICE-OCCUPANCY',
    title: 'Factor de ocupación para oficinas',
    source: 'Decreto 351/79 — Anexo VII',
    sourceSection: 'Apartados 1.4 y 3.1.2',
    summary: 'Para edificios de escritorios y oficinas, el factor de ocupación verificado es una persona cada 8 m².',
    validationType: 'automatic-with-professional-confirmation',
    severity: 'high',
    occupancyFactor: 8,
    sourceUrl: 'https://www.argentina.gob.ar/normativa/recurso/32030/dto351-1979-anexo7/htm',
    checkedAt: '2026-08-07',
    ruleVersion: '1.0.0',
    requiredInputs: [],
  },
];
