import { useMemo, useState } from 'react';
import { createCorporateTemplate, duplicateCorporateTemplate, readCorporateAssetFile } from '../branding/corporateTemplate';
import { resolveDocumentBranding } from '../branding/brandingService';
import { useEditor } from '../store/EditorContext';

const fields = {
  identity: [['companyName', 'Nombre comercial'], ['legalName', 'Razón social'], ['cuit', 'CUIT']],
  contact: [['address', 'Domicilio'], ['phone', 'Teléfono'], ['email', 'Correo'], ['website', 'Web']],
  professional: [['professionalName', 'Nombre profesional'], ['professionalLicense', 'Matrícula']],
  design: [['headerText', 'Texto de encabezado'], ['footerText', 'Texto de pie']],
};

const AssetField = ({ label, kind, template, field, asset, onAsset, onRemove }) => <label className="corporate-asset-field"><span>{label}</span>{asset?.dataUrl ? <img src={asset.dataUrl} alt={label} /> : <small>Sin archivo</small>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) onAsset(file, kind, field); event.target.value = ''; }} />{template[field] && <button type="button" onClick={() => onRemove(template[field], field)}>Quitar</button>}</label>;

const CorporateTemplatePanel = () => {
  const { state, upsertCorporateTemplate, removeCorporateTemplate, setSelectedCorporateTemplate, upsertCorporateAsset, removeCorporateAsset } = useEditor();
  const [error, setError] = useState('');
  const templates = state.document.corporateTemplates || [];
  const selected = templates.find(({ id }) => id === state.document.selectedCorporateTemplateId) || null;
  const branding = useMemo(() => resolveDocumentBranding(state.document), [state.document]);
  const create = () => { const template = createCorporateTemplate({ name: `Plantilla ${templates.length + 1}` }); upsertCorporateTemplate(template); setSelectedCorporateTemplate(template.id); };
  const update = (field, value) => selected && upsertCorporateTemplate(createCorporateTemplate({ ...selected, [field]: value }));
  const upload = async (file, kind, field) => { try { setError(''); const asset = await readCorporateAssetFile(file, kind); upsertCorporateAsset(asset); update(field, asset.id); } catch (uploadError) { setError(uploadError.message); } };
  const removeAsset = (id, field) => { update(field, null); removeCorporateAsset(id); };
  return <section className="corporate-template-editor"><div className="corporate-template-toolbar"><select aria-label="Plantilla predeterminada" value={selected?.id || ''} onChange={(event) => setSelectedCorporateTemplate(event.target.value)}><option value="">Sin plantilla</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select><button type="button" onClick={create}>Nueva</button><button type="button" disabled={!selected} onClick={() => { const copy = duplicateCorporateTemplate(selected); upsertCorporateTemplate(copy); setSelectedCorporateTemplate(copy.id); }}>Duplicar</button><button type="button" disabled={!selected} onClick={() => removeCorporateTemplate(selected.id)}>Eliminar</button></div>
    {!selected ? <div className="corporate-template-empty">Creá o elegí una plantilla. Sin plantilla, el informe conserva el diseño actual.</div> : <div className="corporate-template-layout"><div className="corporate-template-form"><label>Nombre de plantilla<input value={selected.name} maxLength="80" onChange={(event) => update('name', event.target.value)} /></label>{Object.entries(fields).map(([section, items]) => <fieldset key={section}><legend>{{ identity: 'Identidad', contact: 'Contacto', professional: 'Profesional', design: 'Diseño' }[section]}</legend>{items.map(([field, label]) => <label key={field}>{label}<input value={selected[field]} maxLength="240" onChange={(event) => update(field, event.target.value)} /></label>)}{section === 'design' && <div className="corporate-colors"><label>Color principal<input type="color" value={selected.primaryColor || '#0F172A'} onChange={(event) => update('primaryColor', event.target.value)} /></label><label>Color secundario<input type="color" value={selected.secondaryColor || '#2563EB'} onChange={(event) => update('secondaryColor', event.target.value)} /></label></div>}</fieldset>)}<fieldset><legend>Recursos</legend><AssetField label="Logo" kind="logo" field="logoAssetId" template={selected} asset={branding.logo} onAsset={upload} onRemove={removeAsset} /><AssetField label="Firma" kind="signature" field="signatureAssetId" template={selected} asset={branding.signature} onAsset={upload} onRemove={removeAsset} /><AssetField label="Sello" kind="stamp" field="stampAssetId" template={selected} asset={branding.stamp} onAsset={upload} onRemove={removeAsset} /></fieldset><fieldset><legend>Opciones</legend>{[['showPageNumber', 'Número de página'], ['showGeneratedDate', 'Fecha de generación'], ['showProfessionalSignature', 'Mostrar firma']].map(([field, label]) => <label className="corporate-check" key={field}><input type="checkbox" checked={selected[field]} onChange={(event) => update(field, event.target.checked)} />{label}</label>)}</fieldset>{error && <div className="alert alert-danger">{error}</div>}</div>
      <div className="corporate-a4-preview" style={{ '--brand-primary': branding.colors.primary, '--brand-secondary': branding.colors.secondary }}><header>{branding.logo?.dataUrl && <img src={branding.logo.dataUrl} alt="Logo" />}<div><b>{selected.companyName || 'Nombre comercial'}</b><small>{selected.headerText || selected.legalName || 'Encabezado del documento'}</small></div></header><main><h4>Informe técnico</h4><p>{selected.address || 'Domicilio'} · {selected.phone || 'Teléfono'}</p><div /><div /><div className="short" /><h5>Contenido del informe</h5><div /><div /></main>{selected.showProfessionalSignature && <section className="corporate-preview-signature">{branding.signature?.dataUrl && <img src={branding.signature.dataUrl} alt="Firma" />}{branding.stamp?.dataUrl && <img src={branding.stamp.dataUrl} alt="Sello" />}<span>{selected.professionalName || 'Profesional'}<small>{selected.professionalLicense || 'Matrícula'}</small></span></section>}<footer><span>{selected.footerText || selected.website || 'Pie de página'}</span>{selected.showPageNumber && <b>1</b>}</footer></div></div>}
  </section>;
};

export default CorporateTemplatePanel;
